### ISSUE TITLE
[Bug] Map does not render

### ISSUE THREAD

**Issue by samyrataylor** [Bulldog83/JustMap#33]
Hi,

Mini map shows but doesn't render map, only entities. See [Screen Shot](https://user-images.githubusercontent.com/15961687/79395073-d9fe9580-7f46-11ea-817e-9ac4027ec965.png)
This happens on the server (with mod install and without) and in singleplayer.

I have tried removing all other mods (except fabric api) on both the server and in singleplayer, I've removed the justmap folder and had the same issue. 

Thanks

**Comment by samyrataylor** [comment]
I've got it to work with no other mods on both single and multiplayer by deleting my minecraft folder and completely reinstalling it fresh on both mine and my server, with completely new worlds. However when I add another mod it causes a crash. Both mods work fine by themselves.

From my log file:

```
[19:20:16] [main/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at ru.bulldog.justmap.map.data.MapCache.getChunk(MapCache.java:270) ~[justmap-1.1.35-20w14a.jar:?]
	at ru.bulldog.justmap.map.data.MapCache.getChunk(MapCache.java:262) ~[justmap-1.1.35-20w14a.jar:?]
	at ru.bulldog.justmap.map.data.MapCache.getChunk(MapCache.java:258) ~[justmap-1.1.35-20w14a.jar:?]
	at ru.bulldog.justmap.map.data.MapCache.update(MapCache.java:144) ~[justmap-1.1.35-20w14a.jar:?]
	at ru.bulldog.justmap.map.minimap.Minimap.prepareMap(Minimap.java:213) ~[justmap-1.1.35-20w14a.jar:?]
	at ru.bulldog.justmap.map.minimap.Minimap.update(Minimap.java:90) ~[justmap-1.1.35-20w14a.jar:?]
	at ru.bulldog.justmap.client.JustMapClient.lambda$onInitializeClient$0(JustMapClient.java:31) ~[justmap-1.1.35-20w14a.jar:?]
	at net.minecraft.class_310.handler$zdc000$tick(class_310.java:4106) ~[intermediary-fabric-loader-0.8.2+build.194-20w14a.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1554) ~[intermediary-fabric-loader-0.8.2+build.194-20w14a.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:977) ~[intermediary-fabric-loader-0.8.2+build.194-20w14a.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:632) [intermediary-fabric-loader-0.8.2+build.194-20w14a.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-fabric-loader-0.8.2+build.194-20w14a.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[19:20:20] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_nether
[19:20:20] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_end
[19:20:20] [Server thread/INFO]: Stopping server
```

Thanks

**Comment by samyrataylor** [comment]
Upgraded to 20w15a and no longer having this issue.
