### ISSUE TITLE
Conflict with CraftPresence

### ISSUE THREAD

**Issue by Nanogamer7** [Bulldog83/JustMap#40]
I get a conflict between Just Map 1.0.55 (1.15.2) and Craft Presence 1.6.1:
```
FATAL ERROR in native method: Thread[CraftPresence,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglGetIntegerv(Native Method)
	at org.lwjgl.opengl.GL11C.glGetInteger(GL11C.java:852)
	at org.lwjgl.opengl.GL11.glGetInteger(GL11.java:2673)
	at net.minecraft.class_4493.method_21923(class_4493.java:1769)
	at com.mojang.blaze3d.systems.RenderSystem.maxSupportedTextureSize(RenderSystem.java:1065)
	at net.minecraft.class_1059.<init>(class_1059.java:93)
	at ru.bulldog.justmap.util.SpriteAtlas.<clinit>(SpriteAtlas.java:8)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.gitlab.cdagaming.craftpresence.utils.FileUtils.getClassNamesMatchingSuperType(FileUtils.java:249)
	at com.gitlab.cdagaming.craftpresence.utils.gui.GuiUtils.getGUIs(GuiUtils.java:267)
	at com.gitlab.cdagaming.craftpresence.utils.gui.GuiUtils.onTick(GuiUtils.java:203)
	at com.gitlab.cdagaming.craftpresence.utils.CommandUtils.reloadData(CommandUtils.java:58)
	at com.gitlab.cdagaming.craftpresence.CraftPresence.clientTick(CraftPresence.java:202)
	at com.gitlab.cdagaming.craftpresence.CraftPresence.access$000(CraftPresence.java:51)
	at com.gitlab.cdagaming.craftpresence.CraftPresence$1.run(CraftPresence.java:181)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
The conflict with Craft Presence also happens when only using the two affected mods. Any ideas why this crash might happen? The game also doesn't output a crashreport, but only this error in the output log.

**Comment by Bulldog83** [comment]
It happens because CrafyPresence calls some classes too early. I'll think, what I can do with it.

**Comment by Nanogamer7** [comment]
Apparently I missed the 1.6.5 update for Craft Presence, which resolves this issue. But thank you for responding that quickly and apologies for the inconvenience!
