### ISSUE TITLE
[1.16] Game crashes when another player joins

### ISSUE THREAD

**Issue by AntiFish03** [Bulldog83/JustMap#54]
Game crashes with the following log message when another player joins the game.

```
[20:22:31] [Server thread/INFO]: XXXXXXXXXX joined the game
[20:22:31] [main/INFO]: [CHAT] XXXXXXXXXX joined the game
[20:22:31] [main/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: net.minecraft.class_745 cannot be cast to net.minecraft.class_746
	at ru.bulldog.justmap.map.minimap.Minimap.prepareMap(Minimap.java:256) ~[justmap-1.1.81-1.16-release.jar:?]
	at ru.bulldog.justmap.map.minimap.Minimap.update(Minimap.java:88) ~[justmap-1.1.81-1.16-release.jar:?]
	at ru.bulldog.justmap.client.JustMapClient.lambda$onInitializeClient$0(JustMapClient.java:23) ~[justmap-1.1.81-1.16-release.jar:?]
	at net.minecraft.class_310.handler$zda000$tick(class_310.java:4308) ~[intermediary-1.16.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1575) ~[intermediary-1.16.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:994) ~[intermediary-1.16.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-1.16.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-1.16.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.8+build.202.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.8+build.202.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.8+build.202.jar:?]
```

**Comment by AntiFish03** [comment]
Thanks @Bulldog83! Works great! Sorry for the slow feedback.
