### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Boobies** [Bulldog83/JustMap#57]
I am unable to pinpoint this one exactly but sometimes this just happened to me twice in a row: I was fast flying in Creative exploring the map and when I switched to the world map it started lagging and then the game crashed. Sometimes it seemed to think I wanted to save a new waypoint just before the crash although I didn't select that.

The stacktrace does not look particularly helpful to me:

`
net.fabricmc.loader.api.EntrypointException: Could not look up entries for entrypoint client!
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:151)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:198)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
`

**Comment by Bulldog83** [comment]
Post full crash log, please. Via pasetbin, GitHub Gist or something same.

**Comment by Bulldog83** [comment]
As I understand, the problem was gone.
