### ISSUE TITLE
Crash: java.lang.IllegalArgumentException: Invalid Line

### ISSUE THREAD

**Issue by blizzard4591** [Bulldog83/JustMap#76]
Dear developer,

I am using version 1.1.99-1.16.1-release, and I get the following crash:

> java.lang.IllegalArgumentException: Invalid Line: Point [422.000000, 90.000000]: Point [421.174150, 89.506665]! Lenght: 0.000000.
	at ru.bulldog.justmap.util.math.Line.<init>(Line.java:22)
	at ru.bulldog.justmap.util.math.Line.<init>(Line.java:10)
	at ru.bulldog.justmap.map.icon.EntityIcon.draw(EntityIcon.java:57)
	at ru.bulldog.justmap.client.render.MapRenderer.draw(MapRenderer.java:314)
	at net.minecraft.class_329.handler$zfd000$draw(class_329.java:1832)
	at net.minecraft.class_329.method_1753(class_329.java:376)
	at net.minecraft.class_757.method_3192(class_757.java:584)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$51/842741472.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

This does only happen occasionally in my mostly vanilla 1.16.1 world.
If you need more information, I will try to help.

**Comment by Bulldog83** [comment]
Very strange... Here can't be zero. It looks like some glitch. What java version do you use?

**Comment by Bulldog83** [comment]
Any way, I know how to fix it.
