### ISSUE TITLE
GL_INVALID_FRAMEBUFFER_OPERATION error when loading a world

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [Bulldog83/JustMap#83]
This error is logged twice when loading a world. Mod still works (seemingly) without any problem.

```
[10:38:02] [main/ERROR]: OpenGL API ERROR: 1286 (GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL11C.glClear(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11.glClear(GL11.java:1045) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at net.minecraft.class_4493.method_21965(class_4493.java:1543) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_276.method_1230(class_276.java:308) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at ru.bulldog.justmap.util.render.ExtendedFramebuffer.method_1231(ExtendedFramebuffer.java:74) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.util.render.ExtendedFramebuffer.method_1234(ExtendedFramebuffer.java:36) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at net.minecraft.class_276.<init>(class_276.java:45) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at ru.bulldog.justmap.util.render.ExtendedFramebuffer.<init>(ExtendedFramebuffer.java:20) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.render.BufferedRenderer.loadFrameBuffers(BufferedRenderer.java:43) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.map.minimap.Minimap.updateMapParams(Minimap.java:184) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.render.MapRenderer.updateParams(MapRenderer.java:90) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.render.MapRenderer.renderMap(MapRenderer.java:195) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.JustMapClient.lambda$onInitializeClient$2(JustMapClient.java:66) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at net.minecraft.class_329.handler$zdg000$render(class_329.java:1821) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:436) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:765) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1023) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.3+build.207.jar:?]
[10:38:02] [main/ERROR]: OpenGL API ERROR: 1286 (GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL11C.glClear(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11.glClear(GL11.java:1045) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at net.minecraft.class_4493.method_21965(class_4493.java:1543) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_276.method_1230(class_276.java:308) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at ru.bulldog.justmap.util.render.ExtendedFramebuffer.method_1231(ExtendedFramebuffer.java:74) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.util.render.ExtendedFramebuffer.method_1234(ExtendedFramebuffer.java:36) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at net.minecraft.class_276.<init>(class_276.java:45) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at ru.bulldog.justmap.util.render.ExtendedFramebuffer.<init>(ExtendedFramebuffer.java:20) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.render.BufferedRenderer.loadFrameBuffers(BufferedRenderer.java:44) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.map.minimap.Minimap.updateMapParams(Minimap.java:184) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.render.MapRenderer.updateParams(MapRenderer.java:90) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.render.MapRenderer.renderMap(MapRenderer.java:195) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at ru.bulldog.justmap.client.JustMapClient.lambda$onInitializeClient$2(JustMapClient.java:66) ~[justmap-1.2.10-1.16.2-unlimited.jar:?]
	at net.minecraft.class_329.handler$zdg000$render(class_329.java:1821) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:436) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:765) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1023) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.3+build.207.jar:?]
[10:38:02] [main/ERROR]: [Shaders] OpenGL error: 1286 (Invalid framebuffer operation), fbStatus: 36053 (Complete), program: none, at: pre-useProgram
```

**Comment by Bulldog83** [comment]
Do you play on the Mac?

**Comment by 0xfeeddeadbeef** [comment]
@Bulldog83 No. It is Windows 8.1 x64. Nvidia GeForce 1050Ti. Latest drivers. Oracle Java 15.
