### ISSUE TITLE
Massive Lag and Log Spam

### ISSUE THREAD

**Issue by MechanosG** [Bulldog83/JustMap#87]
I have 2 bugs to report.

The first, is a massive lag spike about 75% of the time when I try to submerge myself in water or travel down a narrow hole (with a ladder).  It only happens when "Show Caves" is enabled.  I assume it's some kind of error regarding displaying caves or detecting them?  

The 2nd is this error mentioning entity icons spamming constantly in the log.

> 22:56:21.562
> ru.bulldog.justmap.util.Logger
> main
> [justmap] null
> 22:56:21.562
> ru.bulldog.justmap.util.Logger
> main
> Catching
> java.lang.NullPointerException
> 	at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
> 	at ru.bulldog.justmap.util.ImageUtil.imageExists(ImageUtil.java:34)
> 	at ru.bulldog.justmap.map.icon.EntityHeadIcon.getIcon(EntityHeadIcon.java:38)
> 	at ru.bulldog.justmap.map.icon.EntityIcon.draw(EntityIcon.java:49)
> 	at ru.bulldog.justmap.client.render.BufferedRenderer.drawEntities(BufferedRenderer.java:220)
> 	at ru.bulldog.justmap.client.render.BufferedRenderer.render(BufferedRenderer.java:90)
> 	at ru.bulldog.justmap.client.render.MapRenderer.renderMap(MapRenderer.java:206)
> 	at ru.bulldog.justmap.client.JustMapClient.lambda$onInitializeClient$1(JustMapClient.java:58)
> 	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$null$0(HudRenderCallback.java:27)
> 	at net.minecraft.client.gui.hud.InGameHud.handler$zld000$render(InGameHud:1321)
> 	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:374)
> 	at net.minecraft.client.render.GameRenderer.render(GameRenderer:597)
> 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
> 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
> 	at net.minecraft.client.main.Main.main(Main:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
> 	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
> 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
> 	at java.util.HashMap$Values.forEach(Unknown Source)
> 	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
> 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

I'm betting it's trying to load mob head icons from Age of Exile 1.7.6.  Turning off the heads option for entity radar makes the spam stop.  It might have caused a memory leak, as my game memory quickly filled up while the spam was happening.

MC 1.16.3
Justmap 1.2.13

**Comment by Bulldog83** [comment]
I've fixed NPE with icons (for 1.16.4). But I can't reproduce lags with caves mapping.
